version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_creative_data:/data/db
      - ./data:/data/share

  redis:
    container_name: redis_books
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - cache:/books_data
    networks:
      - app-tier

  redis_insight:
    container_name: redis_insight-books
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    networks:
      - app-tier

volumes:
  mongo_creative_data:
    driver: 'local'
  cache:
