version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_books
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  redis:
    container_name: redis_books
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - cache:/books_data
    networks:
      - app-tier

  redis_insight:
    container_name: redis_insight-books
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    networks:
      - app-tier

volumes:
  cache:
