-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 18:06:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database_course_creative
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `authors` (
                                         `id` INT NOT NULL AUTO_INCREMENT,
                                         `name` VARCHAR(100) NOT NULL,
                                         `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                         `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                         PRIMARY KEY (`id`),
                                         UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publishers` (
                                            `id` INT NOT NULL AUTO_INCREMENT,
                                            `name` VARCHAR(255) NOT NULL,
                                            `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                            `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                            PRIMARY KEY (`id`),
                                            UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books` (
                                       `id` INT NOT NULL AUTO_INCREMENT,
                                       `title` VARCHAR(255) NOT NULL,
                                       `authors_id` INT NULL,
                                       `publishers_id` INT NULL,
                                       `synopsis` VARCHAR(1000) NULL,
                                       `published_at` YEAR NULL,
                                       `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                       `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                       PRIMARY KEY (`id`),
                                       INDEX `fk_books_author1_idx` (`authors_id` ASC) VISIBLE,
                                       INDEX `fk_books_publisher1_idx` (`publishers_id` ASC) VISIBLE,
                                       UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
                                       CONSTRAINT `fk_books_author1`
                                           FOREIGN KEY (`authors_id`)
                                               REFERENCES `authors` (`id`)
                                               ON DELETE CASCADE
                                               ON UPDATE CASCADE,
                                       CONSTRAINT `fk_books_publisher1`
                                           FOREIGN KEY (`publishers_id`)
                                               REFERENCES `publishers` (`id`)
                                               ON DELETE SET NULL
                                               ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
                                       `id` INT NOT NULL AUTO_INCREMENT,
                                       `username` VARCHAR(80) NOT NULL,
                                       `password` VARCHAR(100) NULL,
                                       `email` VARCHAR(255) NULL,
                                       `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                       `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                       PRIMARY KEY (`id`),
                                       UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
                                       UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tags` (
                                      `id` INT NOT NULL AUTO_INCREMENT,
                                      `name` VARCHAR(45) NOT NULL,
                                      `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                      `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                      PRIMARY KEY (`id`),
                                      UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `status` (
                                        `id` INT NOT NULL AUTO_INCREMENT,
                                        `name` VARCHAR(45) NOT NULL,
                                        `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                        `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                        PRIMARY KEY (`id`),
                                        UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `editions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `editions` (
                                          `id` INT NOT NULL AUTO_INCREMENT,
                                          `format` VARCHAR(45) NOT NULL,
                                          `description` VARCHAR(255) NULL,
                                          `image` VARCHAR(255) NULL,
                                          `books_id` INT NOT NULL,
                                          `published_at` YEAR NULL,
                                          `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                          `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                          PRIMARY KEY (`id`, `books_id`),
                                          INDEX `fk_edition_books1_idx` (`books_id` ASC) VISIBLE,
                                          CONSTRAINT `fk_edition_books1`
                                              FOREIGN KEY (`books_id`)
                                                  REFERENCES `books` (`id`)
                                                  ON DELETE CASCADE
                                                  ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libraries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libraries` (
                                           `id` INT NOT NULL AUTO_INCREMENT,
                                           `note` VARCHAR(1000) NULL,
                                           `users_id` INT NULL,
                                           `status_id` INT NULL,
                                           `editions_id` INT NOT NULL,
                                           `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                           `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                           PRIMARY KEY (`id`),
                                           INDEX `fk_library_user1_idx` (`users_id` ASC) VISIBLE,
                                           INDEX `fk_library_status1_idx` (`status_id` ASC) VISIBLE,
                                           INDEX `fk_libraries_editions1_idx` (`editions_id` ASC) VISIBLE,
                                           CONSTRAINT `fk_library_user1`
                                               FOREIGN KEY (`users_id`)
                                                   REFERENCES `users` (`id`)
                                                   ON DELETE SET NULL
                                                   ON UPDATE CASCADE,
                                           CONSTRAINT `fk_library_status1`
                                               FOREIGN KEY (`status_id`)
                                                   REFERENCES `status` (`id`)
                                                   ON DELETE SET NULL
                                                   ON UPDATE CASCADE,
                                           CONSTRAINT `fk_libraries_editions1`
                                               FOREIGN KEY (`editions_id`)
                                                   REFERENCES `editions` (`id`)
                                                   ON DELETE CASCADE
                                                   ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wishlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wishlists` (
                                           `id` INT NOT NULL AUTO_INCREMENT,
                                           `users_id` INT NOT NULL,
                                           `editions_id` INT NOT NULL,
                                           `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                           `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                           PRIMARY KEY (`id`, `users_id`),
                                           INDEX `fk_wishlist_user1_idx` (`users_id` ASC) VISIBLE,
                                           INDEX `fk_wishlists_editions1_idx` (`editions_id` ASC) VISIBLE,
                                           CONSTRAINT `fk_wishlist_user1`
                                               FOREIGN KEY (`users_id`)
                                                   REFERENCES `users` (`id`)
                                                   ON DELETE CASCADE
                                                   ON UPDATE CASCADE,
                                           CONSTRAINT `fk_wishlists_editions1`
                                               FOREIGN KEY (`editions_id`)
                                                   REFERENCES `editions` (`id`)
                                                   ON DELETE CASCADE
                                                   ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_tag_relations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_tag_relations` (
                                                    `books_id` INT NOT NULL,
                                                    `tags_id` INT NOT NULL,
                                                    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                                    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                    PRIMARY KEY (`books_id`, `tags_id`),
                                                    INDEX `fk_books_has_tag_tag1_idx` (`tags_id` ASC) VISIBLE,
                                                    INDEX `fk_books_has_tag_books1_idx` (`books_id` ASC) VISIBLE,
                                                    CONSTRAINT `fk_books_has_tag_books1`
                                                        FOREIGN KEY (`books_id`)
                                                            REFERENCES `books` (`id`)
                                                            ON DELETE CASCADE
                                                            ON UPDATE CASCADE,
                                                    CONSTRAINT `fk_books_has_tag_tag1`
                                                        FOREIGN KEY (`tags_id`)
                                                            REFERENCES `tags` (`id`)
                                                            ON DELETE CASCADE
                                                            ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ratings` (
                                         `id` INT NOT NULL AUTO_INCREMENT,
                                         `rating` INT(5) NULL,
                                         `review` VARCHAR(1000) NULL,
                                         `users_id` INT NULL,
                                         `books_id` INT NULL,
                                         PRIMARY KEY (`id`),
                                         UNIQUE INDEX `user` (`users_id` ASC, `books_id` ASC) VISIBLE,
                                         INDEX `fk_ratings_books1_idx` (`books_id` ASC) VISIBLE,
                                         CONSTRAINT `fk_ratings_users1`
                                             FOREIGN KEY (`users_id`)
                                                 REFERENCES `users` (`id`)
                                                 ON DELETE SET NULL
                                                 ON UPDATE CASCADE,
                                         CONSTRAINT `fk_ratings_books1`
                                             FOREIGN KEY (`books_id`)
                                                 REFERENCES `books` (`id`)
                                                 ON DELETE CASCADE
                                                 ON UPDATE CASCADE)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 18:06:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database_course_creative
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `authors` (
                                         `id` INT NOT NULL AUTO_INCREMENT,
                                         `name` VARCHAR(100) NOT NULL,
                                         `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                         `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                         PRIMARY KEY (`id`),
                                         UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publishers` (
                                            `id` INT NOT NULL AUTO_INCREMENT,
                                            `name` VARCHAR(255) NOT NULL,
                                            `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                            `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                            PRIMARY KEY (`id`),
                                            UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books` (
                                       `id` INT NOT NULL AUTO_INCREMENT,
                                       `title` VARCHAR(255) NOT NULL,
                                       `authors_id` INT NULL,
                                       `publishers_id` INT NULL,
                                       `synopsis` VARCHAR(1000) NULL,
                                       `published_at` YEAR NULL,
                                       `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                       `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                       PRIMARY KEY (`id`),
                                       INDEX `fk_books_author1_idx` (`authors_id` ASC) VISIBLE,
                                       INDEX `fk_books_publisher1_idx` (`publishers_id` ASC) VISIBLE,
                                       UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
                                       CONSTRAINT `fk_books_author1`
                                           FOREIGN KEY (`authors_id`)
                                               REFERENCES `authors` (`id`)
                                               ON DELETE CASCADE
                                               ON UPDATE CASCADE,
                                       CONSTRAINT `fk_books_publisher1`
                                           FOREIGN KEY (`publishers_id`)
                                               REFERENCES `publishers` (`id`)
                                               ON DELETE SET NULL
                                               ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
                                       `id` INT NOT NULL AUTO_INCREMENT,
                                       `username` VARCHAR(80) NOT NULL,
                                       `password` VARCHAR(100) NULL,
                                       `email` VARCHAR(255) NULL,
                                       `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                       `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                       PRIMARY KEY (`id`),
                                       UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
                                       UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tags` (
                                      `id` INT NOT NULL AUTO_INCREMENT,
                                      `name` VARCHAR(45) NOT NULL,
                                      `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                      `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                      PRIMARY KEY (`id`),
                                      UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `status` (
                                        `id` INT NOT NULL AUTO_INCREMENT,
                                        `name` VARCHAR(45) NOT NULL,
                                        `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                        `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                        PRIMARY KEY (`id`),
                                        UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `editions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `editions` (
                                          `id` INT NOT NULL AUTO_INCREMENT,
                                          `format` VARCHAR(45) NOT NULL,
                                          `description` VARCHAR(255) NULL,
                                          `image` VARCHAR(255) NULL,
                                          `books_id` INT NOT NULL,
                                          `published_at` YEAR NULL,
                                          `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                          `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                          PRIMARY KEY (`id`, `books_id`),
                                          INDEX `fk_edition_books1_idx` (`books_id` ASC) VISIBLE,
                                          CONSTRAINT `fk_edition_books1`
                                              FOREIGN KEY (`books_id`)
                                                  REFERENCES `books` (`id`)
                                                  ON DELETE CASCADE
                                                  ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libraries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libraries` (
                                           `id` INT NOT NULL AUTO_INCREMENT,
                                           `note` VARCHAR(1000) NULL,
                                           `users_id` INT NULL,
                                           `status_id` INT NULL,
                                           `editions_id` INT NOT NULL,
                                           `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                           `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                           PRIMARY KEY (`id`),
                                           INDEX `fk_library_user1_idx` (`users_id` ASC) VISIBLE,
                                           INDEX `fk_library_status1_idx` (`status_id` ASC) VISIBLE,
                                           INDEX `fk_libraries_editions1_idx` (`editions_id` ASC) VISIBLE,
                                           CONSTRAINT `fk_library_user1`
                                               FOREIGN KEY (`users_id`)
                                                   REFERENCES `users` (`id`)
                                                   ON DELETE SET NULL
                                                   ON UPDATE CASCADE,
                                           CONSTRAINT `fk_library_status1`
                                               FOREIGN KEY (`status_id`)
                                                   REFERENCES `status` (`id`)
                                                   ON DELETE SET NULL
                                                   ON UPDATE CASCADE,
                                           CONSTRAINT `fk_libraries_editions1`
                                               FOREIGN KEY (`editions_id`)
                                                   REFERENCES `editions` (`id`)
                                                   ON DELETE CASCADE
                                                   ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wishlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wishlists` (
                                           `id` INT NOT NULL AUTO_INCREMENT,
                                           `users_id` INT NOT NULL,
                                           `editions_id` INT NOT NULL,
                                           `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                           `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                           PRIMARY KEY (`id`, `users_id`),
                                           INDEX `fk_wishlist_user1_idx` (`users_id` ASC) VISIBLE,
                                           INDEX `fk_wishlists_editions1_idx` (`editions_id` ASC) VISIBLE,
                                           CONSTRAINT `fk_wishlist_user1`
                                               FOREIGN KEY (`users_id`)
                                                   REFERENCES `users` (`id`)
                                                   ON DELETE CASCADE
                                                   ON UPDATE CASCADE,
                                           CONSTRAINT `fk_wishlists_editions1`
                                               FOREIGN KEY (`editions_id`)
                                                   REFERENCES `editions` (`id`)
                                                   ON DELETE CASCADE
                                                   ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_tag_relations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_tag_relations` (
                                                    `books_id` INT NOT NULL,
                                                    `tags_id` INT NOT NULL,
                                                    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                                    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                    PRIMARY KEY (`books_id`, `tags_id`),
                                                    INDEX `fk_books_has_tag_tag1_idx` (`tags_id` ASC) VISIBLE,
                                                    INDEX `fk_books_has_tag_books1_idx` (`books_id` ASC) VISIBLE,
                                                    CONSTRAINT `fk_books_has_tag_books1`
                                                        FOREIGN KEY (`books_id`)
                                                            REFERENCES `books` (`id`)
                                                            ON DELETE CASCADE
                                                            ON UPDATE CASCADE,
                                                    CONSTRAINT `fk_books_has_tag_tag1`
                                                        FOREIGN KEY (`tags_id`)
                                                            REFERENCES `tags` (`id`)
                                                            ON DELETE CASCADE
                                                            ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ratings` (
                                         `id` INT NOT NULL AUTO_INCREMENT,
                                         `rating` INT(5) NULL,
                                         `review` VARCHAR(1000) NULL,
                                         `users_id` INT NULL,
                                         `books_id` INT NULL,
                                         PRIMARY KEY (`id`),
                                         UNIQUE INDEX `user` (`users_id` ASC, `books_id` ASC) VISIBLE,
                                         INDEX `fk_ratings_books1_idx` (`books_id` ASC) VISIBLE,
                                         CONSTRAINT `fk_ratings_users1`
                                             FOREIGN KEY (`users_id`)
                                                 REFERENCES `users` (`id`)
                                                 ON DELETE SET NULL
                                                 ON UPDATE CASCADE,
                                         CONSTRAINT `fk_ratings_books1`
                                             FOREIGN KEY (`books_id`)
                                                 REFERENCES `books` (`id`)
                                                 ON DELETE CASCADE
                                                 ON UPDATE CASCADE)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
